# Generated by Django 3.2.21 on 2023-11-23 04:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0002_rename_user_habit_owner'),
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitcompletion',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('owner', 'habit', 'completion_date')},
        ),
    ]
