# Generated by Django 3.2.21 on 2023-09-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
    ]
