# Generated by Django 3.2.21 on 2024-02-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
    ]
